### PR TITLE
Update strings.xml - Portuguese version

### PR DESCRIPTION
**Pull request by periclesjr**
@mstevens83 
Portuguese translation!
Here it goes!
Pericles

### CODE REVIEW

**Comment by mstevens83** [comment]
Nice job. I'll merge this into the lang_pt_BR branch.
However, in the last few days I have added/changed a few of this Enlish strings, so there might be a little bit more work to do.

**Comment by periclesjr** [comment]
@mstevens83 Don't worry! Probably,  after the test, we will have more things to suit in the portuguese version.

**Comment by mstevens83** [comment]
I'll make a test build this afternoon. Do you have an Android phone to try it with? If not ask Muki, Louise or Patrick ;-)

**Comment by periclesjr** [comment]
@mstevens83 , I have already asked one to Louise. It is already with me.

**Pull request merged**
